FROM python:3.11-slim

RUN apt-get update && apt-get install -y gcc git && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    dagster \
    dagster-webserver \
    dagster-postgres \
    dagster-dbt \
    dbt-core \
    dbt-clickhouse \
    clickhouse-connect \
    pymongo \
    psycopg2-binary \
    faker \
    psutil \
    boto3

ENV DAGSTER_HOME=/opt/dagster/app
WORKDIR /opt/dagster/app
